### ISSUE TITLE
Error when scanning library

### ISSUE THREAD

**Issue by SenorSmartyPants** [crobibero/jellyfin-plugin-imvdb#1]
I have an IMVDB API entered into the plugin config. But plugin always generates an error.

IMVDB related log entries.

```
[2021-04-03 14:17:05.140 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.IMVDb, Version=2.2021.102.318, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/IMVDb_2.2021.102.318/Jellyfin.Plugin.IMVDb.dll"
[2021-04-03 14:17:38.210 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "IMVDb" "2.2021.102.318"
[2021-04-03 14:30:17.177 -05:00] [ERR] [46] MediaBrowser.Providers.Music.MusicVideoMetadataService: Error in "IMVDb"
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Jellyfin.Plugin.IMVDb.ImvdbProvider.GetSearchResponse(MusicVideoInfo searchInfo, String apiKey, CancellationToken cancellationToken)
   at Jellyfin.Plugin.IMVDb.ImvdbProvider.GetSearchResponse(MusicVideoInfo searchInfo, String apiKey, CancellationToken cancellationToken)
   at Jellyfin.Plugin.IMVDb.ImvdbProvider.GetSearchResults(MusicVideoInfo searchInfo, CancellationToken cancellationToken)
   at Jellyfin.Plugin.IMVDb.ImvdbProvider.GetMetadata(MusicVideoInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

Files named in a couple different styles to see what works

```
<MVDir>/Foo Fighters/This is a Call/This is a Call.mp4
<MVDir>/Weezer - Buddy Holly.mp4
<MVDir>/Beastie Boys/Brass Monkey.mp4
```

JF doesn't seem to grab the artist name from any of these styles.

**Comment by crobibero** [comment]
Fixed in plugin version `2.2021.404.1749`

**Comment by SenorSmartyPants** [comment]
Confirmed. Plugin is now successfully pulling data from IMVDB. Thank you!

**Comment by crobibero** [comment]
@SenorSmartyPants After more testing I found that `<MVDir>/{Artist}/{Title}/{Title}.{ext}` gives the best search result

**Comment by SenorSmartyPants** [comment]
It's identified all but one or two of my videos correctly. I'll move them to that format if I have more problems.
